export { default as ShipmentsTabUseGM65 } from "./shipments-tab-use-gm65"
export { default as ShipmentDetailTab } from "./shipment-detail-tab"
export { default as AuditLogsTab } from "./audit-logs-tab"
export { default as UsersTab } from "./users-tab"
export { default as Spinner } from "./spinner-loading"